extends Node
## Autoload "Sfx": sound effects pool, character voice blips and music with
## cross-fading. Audio files are generated by tools/gen_audio.py.

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"
const VOICE_PITCH := {
	"mira": 1.15, "grin": 0.8, "bellamy": 0.7, "tobi": 1.0, "oddo": 0.9,
	"magpie": 1.6, "sign": 1.3, "narrator": 1.0, "nana": 1.05,
}

var _pool: Array[AudioStreamPlayer] = []
var _cache: Dictionary = {}
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _current_music := ""
var _amb_a: AudioStreamPlayer
var _amb_b: AudioStreamPlayer
var _current_amb := ""
const AMB_DB := -9.0
var _fade := 0.0
var _muted := false
var cues := {}   # how many times each menu cue was asked for (counted even when muted, for the tests)


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_muted = DisplayServer.get_name() == "headless"
	for i in 24:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_pool.append(p)
	_music_a = AudioStreamPlayer.new()
	_music_b = AudioStreamPlayer.new()
	add_child(_music_a)
	add_child(_music_b)
	_amb_a = AudioStreamPlayer.new()
	_amb_b = AudioStreamPlayer.new()
	add_child(_amb_a)
	add_child(_amb_b)


func _exit_tree() -> void:
	for p in _pool:
		p.stop()
		p.stream = null
	for p in [_music_a, _music_b, _amb_a, _amb_b]:
		p.stop()
		p.stream = null
	_cache.clear()


func _stream(path: String) -> AudioStream:
	if _cache.has(path):
		return _cache[path]
	var s: AudioStream = null
	if ResourceLoader.exists(path):
		s = load(path)
	_cache[path] = s
	return s


func _sfx_db() -> float:
	return linear_to_db(maxf(float(Game.settings.get("sfx", 0.8)), 0.0001))


func _music_db() -> float:
	return linear_to_db(maxf(float(Game.settings.get("music", 0.7)), 0.0001))


func play(name: String, pitch: float = 1.0, vol: float = 0.0) -> void:
	if _muted:
		return
	var s := _stream(SFX_DIR + name + ".wav")
	if s == null:
		return
	for p in _pool:
		if not p.playing:
			p.stream = s
			p.pitch_scale = pitch * randf_range(0.97, 1.03)
			p.volume_db = _sfx_db() + vol
			p.play()
			return


## Backing out of a menu: a lower, softer take on the select cue.
func back() -> void:
	cues["back"] = int(cues.get("back", 0)) + 1
	play("menu_select", 0.72, -4.0)


func play_voice(who: String) -> void:
	var pitch: float = VOICE_PITCH.get(who, 1.0)
	play("blip", pitch * randf_range(0.92, 1.08), -6.0)


func _music_stream(name: String) -> AudioStream:
	var s := _stream(MUSIC_DIR + name + ".ogg")
	if s == null:
		s = _stream(MUSIC_DIR + name + ".wav")
	if s is AudioStreamOggVorbis:
		(s as AudioStreamOggVorbis).loop = true
	elif s is AudioStreamWAV:
		var w := s as AudioStreamWAV
		w.loop_mode = AudioStreamWAV.LOOP_FORWARD
		w.loop_begin = 0
		w.loop_end = int(w.get_length() * w.mix_rate)
	return s


func play_music(name: String) -> void:
	if _muted or name == _current_music:
		return
	_current_music = name
	var s := _music_stream(name)
	var old := _music_a if _music_a.playing else _music_b
	var nxt := _music_b if old == _music_a else _music_a
	if old.playing:
		var tw := create_tween()
		tw.tween_property(old, "volume_db", -60.0, 1.2)
		tw.tween_callback(old.stop)
	if s:
		nxt.stream = s
		nxt.volume_db = -60.0
		nxt.play()
		var tw2 := create_tween()
		tw2.tween_property(nxt, "volume_db", _music_db(), 1.0)


## Looping background ambience (wind, crickets, drips...), cross-faded.
func play_ambience(name: String) -> void:
	if _muted or name == _current_amb:
		return
	_current_amb = name
	var old := _amb_a if _amb_a.playing else _amb_b
	var nxt := _amb_b if old == _amb_a else _amb_a
	if old.playing:
		var tw := create_tween()
		tw.tween_property(old, "volume_db", -60.0, 1.5)
		tw.tween_callback(old.stop)
	if name == "":
		return
	var s := _music_stream(name)
	if s:
		nxt.stream = s
		nxt.volume_db = -60.0
		nxt.play()
		var tw2 := create_tween()
		tw2.tween_property(nxt, "volume_db", _amb_db(), 2.0)


func _amb_db() -> float:
	return linear_to_db(maxf(float(Game.settings.get("sfx", 0.8)), 0.0001)) + AMB_DB


func stop_music(fade: float = 1.0) -> void:
	_current_music = ""
	for p in [_music_a, _music_b]:
		if p.playing:
			var tw := create_tween()
			tw.tween_property(p, "volume_db", -60.0, fade)
			tw.tween_callback(p.stop)


func refresh_volume() -> void:
	for p in [_music_a, _music_b]:
		if p.playing:
			p.volume_db = _music_db()
	for p in [_amb_a, _amb_b]:
		if p.playing:
			p.volume_db = _amb_db()
